### ISSUE TITLE
Should/could api to create Tasks instead of Cmds for chain-ability?

### ISSUE THREAD

**Issue by tracker-common** [elm-lang/navigation#29]
I have the following situation: I want to do some http, then based on the response I do a navigation or something else.  Currently, my only approach is to have a Msg from the Http.send that my update loop responds to, but I would like to be able to use Task.andThen to chain the http call and conditionally my navigation.  However, since navigation calls only result in Cmds, I can't use andThen on them, which makes my code a little more verbose and expands my Msg space.

Am I missing a better way to do this?  Is the proposed solution appropriate?  Thoughts?

Thanks.

(cc @jschomay)

**Comment by mreriklott** [comment]
Yeah, I've bumped up against this issue multiple times in our elm single page app as well (and also again right now). I need to chain a navigation task after an http request, but can't due to Navigation only returning Cmds.

Each "page" in our SPA has a `load` function that constructs the page's model in its entirety before it is added to the state tree and displayed. Example:

```
load : Session -> (Model -> msg) -> Cmd msg
load session toMsg =
    Task.map3 initialModel
        (getAccounts session)
        (getInvoices session)
        (getBillings session)
        |> Task.onError initialModelFromError
        |> Task.perform toMsg
```

If `getAccounts` returns an empty list from the backend server, I'd ideally redirect to different page from within the task chain itself, but cannot since navigation cannot be chained. arg.

Is there any interest in providing the Navigation functions as tasks instead of Cmds (or both, like http)?

**Comment by mreriklott** [comment]
I have the same issue. I want to make an http request, followed by a chained navigation task. The navigation destination is generated based on the return value of the http request.

**Comment by evancz** [comment]
That's the state of things for now. I can imagine expanding a bunch of APIs to expose `Task` instead of `Cmd` but that is not under consideration at the moment.

I don't think this issue clearly tracks any work, so I am going to close.
