### ISSUE TITLE
Fast repeated mouse clicks not registered in Chrome

### ISSUE THREAD

**Issue by mikaxyz** [elm-lang/navigation#30]
When clicking repeatedly and fast enough on a link the app is not responding (i.e. no trigger of OnLocationChange). Using keyboard to "click" the links works as expected.

The [Example.elm](https://github.com/elm-lang/navigation/blob/master/examples/Example.elm) app has this problem (tested in Chrome on Mac OS).

**Comment by mikaxyz** [comment]
Investigated this and it seems this is a problem in plain javascript implementation (see [gist](https://gist.github.com/mikaxyz/ea0a78247e2acc457146c0d1b5f3057b)) using `window.onhashchange` also so maybe close this issue. Would be nice if someone had any workaround/info on it. Is it a "security" feature in chrome to prevent links changing while user is about to click them maybe?

**Comment by evancz** [comment]
Based on what you are saying, I am going to assume that the behavior is the same in JS, without Elm involved at all. In that case, this issues should be closed.

I don't have any particular insight on the browser behavior unfortunately.

If you find out what the root cause is, and find that other projects protect against it in some way, please open a new issue explaining the full situation!
