### ISSUE TITLE
Change url without notifying the update function

### ISSUE THREAD

**Issue by lorenzo** [elm-lang/navigation#35]
This package seems to guide you to switch "pages" only by listening to changes in the `Location`. While this is often what users need, there are many cases where it is not desirable to notify the update function after manually calling `newUrl` or `modifyUrl`.

Consider this case:

```elm
update msg model =
    SetRoute route ->
        setRoute route model -- This is called on init, matches the route and changes the state

    ShowPollResultsClicked ->
        model
           |> changeStuff
           ! [ Http.send FetchStuff httpRequest, modifyUrl urlForPollResults] 


setRoute route model =
    case route of
       ShowResults ->
           model -- We want this logic here to load the right stuff on first page load
               |> changeStuff
               ! [ Http.send FetchStuff httpRequest] 
```

We face here a problem. Either the message for showing the page is **always** driven by `SetRoute` or we will have to live with the fact that the `Http` request will be done twice. Once for `ShowPollResults` and once after the `update` function is notified of the url change.

I consider that there should be an option to bypass this notification. Otherwise you are forced to implement your application logic around the idea that changing from one state to the other needs to be handled only from url changes (at least those parts of the state you want to persist in the URL)

There is an easy solution of this: expose versions of `newUrl` and `modifyUrl` that discard doing the url change notification back to the `update` function.

**Comment by TheZoq2** [comment]
I ran into this same issue and I agree, this is something that would be very nice if it was handled by the library

**Comment by SergKam** [comment]
Run into the same problem. And it is the showstopper for me. 
I have an input and its model field ("filter" for example) and the URL param (also filter).
If the user changes input I update URL param, if the user updates URI I want to update the input(and its model).
So if the user changes input,  witch sets new URL and this  URL change fireback event (asyncronosly) I cannot say is the origin of this change the input or URL. 
This creates a lot of loops (when new values in input reverted by the old value from URL change event. )

In the end, I had to copy/paste the Native implementation from here to my project just to remove this https://github.com/elm-lang/navigation/blob/master/src/Native/Navigation.js#L23
and this https://github.com/elm-lang/navigation/blob/master/src/Native/Navigation.js#L32 lines.

**Comment by sandust** [comment]
You can exposoe window.history.replaceState or window.history.pushState via ports as a work around until a convenient way is available. It does not trigger Navigation.OnLocationChange and does change the url.

`window.history.replaceState(null, null, "#your-hash-url?param=1")`

Not sure about browser compatibility, have only tried it in chrome so far.

**Comment by jschomay** [comment]
This is a serious issue for me as well.  Unless using an anchor tag, I want to control my app logic via the usual TEA loop, and I see changing the url in the address bar as a *side effect, no different than rendering some DOM.*

I feel this breaks TEA in two significant ways: 

1. every event from the user (clicking a button for example) turns into two events (button click, plus navigate), when there really was only one event outside of the system
2. my url bar becomes a stateful store (as opposed to a parameterized event), so now I have two stores that I have to manage

I am using elm in production, but this is making the process difficult, so please consider @lorenzo's suggestion sooner rather than later.  Thank you.

**Comment by jschomay** [comment]
I have an additional thought, based around a point of confusion I had with this libary. 

I found it odd that this library depends on the `Navigation.program` function.  Normal libraries cannot make their own `program` as far as I know.  After thinking about it, I understand the `(Location -> msg)` parameter as analogous to a subscription to url changes.

The cause for my confusion is that this is baked into `Navigation.program` instead of via a `Navigation.subscription` as other libraries do.  I do not know if there is an intrinsic reason for not doing it this way, but I feel it would be better because 1) it follows a common pattern for subscriptions that we are used to with other packages, 2) it gives us more control of that subscription, and 3) it is easier to think about url changes as something we can subscribe to.

I realize you are making big changes around this area in 0.19, but I wanted to share my feedback after using this library for your consideration.

**Comment by SergKam** [comment]
Sorry, @lorenzo Why did you close it? Is it solved or irrelevant any more?

**Comment by noiseOnTheNet** [comment]
@lorenzo I also need this to be fixed: please reopen this issue

**Comment by lorenzo** [comment]
It was clear to me after speaking to evan that this is not going to be fixed, at least not in the way I proposed. I'm using a patch fork of this repo to overcome my immediate issue https://github.com/lorenzo/navigation

**Comment by SergKam** [comment]
@lorenzo Can you elaborate on this a bit more? We all need to know what Evan plans to do with this issue.
This is serious, we can not just "let it go". Please do not close the issue if it is not resolved.

**Comment by kspeakman** [comment]
What we currently do to work-around is update the model like normal (including changing the current route), then call `Navigation.newUrl`, but when the location update comes back thru we only process it if it is different from the current route. So the location update basically gets ignored unless it was changed externally.

**Comment by TheZoq2** [comment]
That's what I do as well. It's a bit cumbersome but it does the job

**Comment by SergKam** [comment]
@kspeakman @TheZoq2 It will not work correctly in all cases, I tried it.  It works only if the user changes URL slowly and his browser is fast. The fireback is async event. If user typing very fast, your internal model can expect the new url(to ignore it) but can get the old one (different from new expected) so you switch model back to old. Then you receive new ... and it loops indefinitely.  You have to store the history of all URL changes to avoid it. The only option, just do not fire events back.

**Comment by TheZoq2** [comment]
Oh right, that's a good point. In my case it's not a huge issue because the user will (should) never make quick big modifications to the url. I only use it to allow page refreshes to get back to the same place in a list.

**Comment by kspeakman** [comment]
@SergKam You are right. If you are calling `newUrl` from user typing, it is not going to work well. I have the user hit Enter to trigger url updates (and searches) to avoid that.

But in general, I agree with the thread's sentiment that Navigation worked quite differently from expected when my team first started trying to use it. We expected `newUrl` to be a side effect, not to trigger a location update in Elm again. We expected location updates to be only for external changes. There was precious little guidance about how to properly use it from end to end. The way it currently works involves some redundancy.

One positive thing I will say about the current setup -- it forces you to dogfood your own location updates.
