### ISSUE TITLE
Provide a subscription

### ISSUE THREAD

**Issue by sporto** [elm-lang/navigation#4]
I would like to upgrade Hop to 0.17. Hop aims to be an easy to use solution for routing that covers parsing, reverse routing, nested routes, query string manipulation, hash or push state routing, etc.

In 0.16 Hop was using elm-history as an input signal and provided another signal to the application. I think this was a good model for a router and I would like to migrate to 0.17 without having to change Hop into something completely different.

To do this, it will be great if Navigation can provide a subscription that Hop can listen to (Then Hop will provide another subscription for the app). Please consider this.

**Comment by evancz** [comment]
I specifically chose not to provide a subscription because it does not make sense for two totally independent components to both be reading the overall path. If components are nested, you should be composing your URL parsers with something like `(</>)`.

To put it another way, I think you can do everything you used to with the API as is. You were using signals before. This meant there was a single point of entry, feeding into start app. From there you would do whatever within your app. It's the same now. Instead of a signal, things go into `urlUpdate`. If you don't like the `Navigation.program` API, wrap it up. It's a function.

Hopefully that's enough to get things going.

**Comment by sporto** [comment]
I don't fully understand your concern, isn't this why we have a `subscriptions` attribute in Html.App?

People would do something like:
```
    Html.App.program
      { init = init
      , view = view
      , update = update
      , subscriptions = [ subscriptionFromYourRouter ]
      }
```

Also, is wrapping Html.App a good idea? Another thing might come along that also want to wrap Html.App and then how to do you use them together?

**Comment by evancz** [comment]
There's more discussion of the design concerns in the #elm-dev channel on slack.

Maybe it'll be problematic some day. Right now it seems fine. Part of why Elm is good is because I wait until we have concrete scenarios before designing things. Right now, there are no concrete problems that anyone can see. If some come up, we can fix it then.
